# yaml-language-server: $schema=https://raw.githubusercontent.com/akatranlp/concur/refs/heads/main/config.schema.json

prefix:
  template: "{{.Time}} {{.Padding}}{{.Name}}"
  padPrefix: true

runBefore:
  commands:
    - command: make infra/up
    - command: make generate

commands:
  - command: make infra/logs
    name: infra
    color: "#8ec07c"
    bold: true
  - command: go tool air
    name: backend
    color: "#458588"
    bold: true
  - command: yarn dev:tsr
    name: tsr
    cwd: ./frontend
    color: "#cc241d"
    bold: true
  - command: yarn dev:vite
    name: frontend
    cwd: ./frontend
    color: "#fe8019"
    bold: true

status:
  enabled: true
  printInterval: 200ms
  checks:
    - type: command
      command: make infra/status
      interval: 1s
    - type: http
      url: http://localhost:3000/health
      interval: 200ms
      template: |-
        {{- if .Error }}{{ .Error }}{{ else -}}
        {{- $body := jsonParse .Body -}}
        {{ .URL }} -> {{ .StatusCode }} Status: {{ index $body "status" }}
        {{- end -}}

runAfter:
  commands:
    - command: make infra/stop
