# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  AUTH_CLIENT_ID: ""
  AUTH_CLIENT_SECRET: ""
  AUTH_SCOPES: YXBp
  SMTP_USER: YXBwQGdpdC1jbGFzc3Jvb21zLmRldg==
  SMTP_PASSWORD: cGFzc3dvcmQ=
