#ENC[AES256_GCM,data:3+pexUQWjkdX8GH9wN3TknWWULqHXp1KPJ7j5qk3izKnB4AKNyYjIrJeW5SoYKC4WCUSn/+buvBKMA==,iv:9nZ53x06MPH+LWBbg61BFZ5VSGsT2DoziR87e2rHl5w=,tag:FhG+5MLTmRN1nh+swe/eFQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:YJAmZQQcyytkG6f3lDjf9AMFhCC2kIh3G+cM9w==,iv:xa90ka8/duUGFdhEA2+Vlx+7mxJEeKYpyLSW8AlHxxs=,tag:iFzt3AdWTAVK5tJ3WCCsUg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:X1sFY4Dg9f2uLaBZpmm8WrCy9UMhhV5f0wH7NMTPvIFVMB1BrvUXFiknfOQ=,iv:P02nElFJHh3Z4CBsxzS2hnIUW/A30yrJ1WtcwYNfdR4=,tag:gvCFOUULN/oLt5Cmt5PnbQ==,type:str]
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:HqJuOx5O3CRZ58WrbO7DeSZCUYzmMbzfPlZhz9nNDexYHpItsPMpCdbqqGnolHbJeBEDN6p7zAeoCrHGVTD4W2KSFyZEWqPeKBunP++XUPChjafX+0R2Uw==,iv:Oh44zBstiFfvtkwWGBbi1YacdPqyfy6vcbJ7lm2nGUA=,tag:P5MvBOYmRaH0a8iK8ZEY0A==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VADMj+j35oh9zMrKWAdBZL2UHzkvPt/BEGegfAqzhcH1gWqM48I5s6aO5GQtPaE9VyluhFtH7evt+YOCitEzlqoeU+5XQQ4tMDUVMgRt0cbtfcdZK+TyDpctrAawUl1k,iv:BUpZGoBSUI9BWCscUnfDlbe+8+awqJfevCV44V+fbb8=,tag:fA+p0hpmBDcLS5L26RpBsQ==,type:str]
    AUTH_SCOPES: ENC[AES256_GCM,data:GWikZQ==,iv:aBXlrGW5MVDu4AhkSPI6awnqDnDhcMdANW8PvRZ5/nE=,tag:lSz2EHT4mZ6Z2HLLdHJwDA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:4j2ikYCJ+aVW1eKTS+hyceq29L/lGWCop9daTbiY/vc=,iv:HmAB09a1mXaDkgvMSkaVro3eFAtnG3obHkxFlxCb4GE=,tag:IZRzBU5EzfbE+FX7B8fHDw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:5KG27ns7KGFLWEuD,iv:M+PBuyM6bLVqeyMRAh8quF9YPk3mnyBxJSEslyvbmsY=,tag:RJDWTmt6NsyoN8ZMHDBrVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age120smthme2cve6kfak2gpnle5nqzzamnj2rmpw9gmr9dwyyvnfahq0fq454
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dko4dzhseEd5eG5BcEEx
            YzNKblliRTFCYkhIdFIyYTFlU1FuWXdoM21ZCmRVZzRpWWFScU5HWUI1VE9qRUVE
            eWdrMzNCYlc4elRLRVRuTTQ4UDJNbWcKLS0tIE1iNWxxOWt5ZzluSWh5MUE1ay9v
            R2xEZkJzeXlmTDRWUmhYQ3k5RldtcFEKTOhdcoyeTu+SBvg4xPU8cW4/+hh8zPuc
            shFbieDJ4t4c3QkIA4s2K9mNaTQRGEmKNbWeX/2DiSD3tExEINQE6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T12:09:22Z"
    mac: ENC[AES256_GCM,data:9iUu4fop0v6ekQ0nRJOlC5GMnSOSVjbGuNqVvC7bCeFAFKIOJl7x6T+YzDCL4uavJUebcW8pN0C4DsRHjm6LLhT+64riA1CerfzWTNQBesnvZoQFqNXiAlMZdvz9Mcu4dU9gfT/vaxFlH/R0AZKhT2Eoa/KKWkLeM8F54VfMQrw=,iv:L+m9GHc7bxRcUpsk7FaSmGf8A559gDeFT6HCMstNnQk=,tag:nDRzMOqnFTf/9V4f7I7dJA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
