/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Classroom } from './classroom';
import { DatabaseAssignmentDate } from './database-assignment-date';
 /**
 * 
 *
 * @export
 * @interface ActiveAssignmentResponse
 */
export interface ActiveAssignmentResponse {

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    acceptableSince?: string;

    /**
     * @type {Array<DatabaseAssignmentDate>}
     * @memberof ActiveAssignmentResponse
     */
    assignmentDates: Array<DatabaseAssignmentDate>;

    /**
     * @type {Classroom}
     * @memberof ActiveAssignmentResponse
     */
    classroom: Classroom;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    classroomId: string;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    createdAt: string;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    description: string;

    /**
     * @type {boolean}
     * @memberof ActiveAssignmentResponse
     */
    gradingJUnitAutoGradingActive: boolean;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    id: string;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    name: string;

    /**
     * @type {number}
     * @memberof ActiveAssignmentResponse
     */
    templateProjectId: number;

    /**
     * @type {string}
     * @memberof ActiveAssignmentResponse
     */
    updatedAt: string;
}
