/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ManualGradingRubric } from './manual-grading-rubric';
 /**
 * 
 *
 * @export
 * @interface AssignmentGradingResponse
 */
export interface AssignmentGradingResponse {

    /**
     * @type {boolean}
     * @memberof AssignmentGradingResponse
     */
    gradingJUnitAutoGradingActive: boolean;

    /**
     * @type {Array<ManualGradingRubric>}
     * @memberof AssignmentGradingResponse
     */
    gradingManualRubrics: Array<ManualGradingRubric>;
}
