/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface Classroom
 */
export interface Classroom {

    /**
     * @type {boolean}
     * @memberof Classroom
     */
    archived: boolean;

    /**
     * @type {boolean}
     * @memberof Classroom
     */
    createTeams: boolean;

    /**
     * @type {string}
     * @memberof Classroom
     */
    description: string;

    /**
     * @type {number}
     * @memberof Classroom
     */
    groupId: number;

    /**
     * @type {string}
     * @memberof Classroom
     */
    id: string;

    /**
     * @type {number}
     * @memberof Classroom
     */
    maxTeamSize: number;

    /**
     * @type {number}
     * @memberof Classroom
     */
    maxTeams: number;

    /**
     * @type {string}
     * @memberof Classroom
     */
    name: string;

    /**
     * @type {User}
     * @memberof Classroom
     */
    owner: User;

    /**
     * @type {number}
     * @memberof Classroom
     */
    ownerId: number;

    /**
     * @type {boolean}
     * @memberof Classroom
     */
    studentsViewAllProjects: boolean;
}
