/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAssignmentRequest
 */
export interface CreateAssignmentRequest {

    /**
     * @type {string}
     * @memberof CreateAssignmentRequest
     */
    description: string;

    /**
     * @type {string}
     * @memberof CreateAssignmentRequest
     */
    dueDate?: string;

    /**
     * @type {string}
     * @memberof CreateAssignmentRequest
     */
    name: string;

    /**
     * @type {number}
     * @memberof CreateAssignmentRequest
     */
    templateProjectId: number;
}
