/* tslint:disable */
/* eslint-disable */
/**
 * Gitlab Classroom API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DatabaseUser
 */
export interface DatabaseUser {

    /**
     * @type {string}
     * @memberof DatabaseUser
     */
    gitlabEmail?: string;

    /**
     * @type {number}
     * @memberof DatabaseUser
     */
    id?: number;

    /**
     * @type {string}
     * @memberof DatabaseUser
     */
    name?: string;
}
