/* tslint:disable */
/* eslint-disable */
/**
 * Gitlab Classroom API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DatabaseClassroom } from './database-classroom';
import { DatabaseRole } from './database-role';
import { DatabaseTeam } from './database-team';
import { DatabaseUser } from './database-user';
 /**
 * 
 *
 * @export
 * @interface DefaultControllerGetOwnedClassroomMemberResponse
 */
export interface DefaultControllerGetOwnedClassroomMemberResponse {

    /**
     * @type {DatabaseClassroom}
     * @memberof DefaultControllerGetOwnedClassroomMemberResponse
     */
    classroom?: DatabaseClassroom;

    /**
     * @type {string}
     * @memberof DefaultControllerGetOwnedClassroomMemberResponse
     */
    gitlabUrl?: string;

    /**
     * @type {DatabaseRole}
     * @memberof DefaultControllerGetOwnedClassroomMemberResponse
     */
    role?: DatabaseRole;

    /**
     * @type {DatabaseTeam}
     * @memberof DefaultControllerGetOwnedClassroomMemberResponse
     */
    team?: DatabaseTeam;

    /**
     * @type {DatabaseUser}
     * @memberof DefaultControllerGetOwnedClassroomMemberResponse
     */
    user?: DatabaseUser;
}
