/* tslint:disable */
/* eslint-disable */
/**
 * Gitlab Classroom API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DatabaseUser } from './database-user';
 /**
 * 
 *
 * @export
 * @interface DefaultControllerGetOwnedClassroomResponse
 */
export interface DefaultControllerGetOwnedClassroomResponse {

    /**
     * @type {boolean}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    createTeams?: boolean;

    /**
     * @type {string}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    description?: string;

    /**
     * @type {string}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    gitlabUrl?: string;

    /**
     * @type {number}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    groupId?: number;

    /**
     * @type {string}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    id?: string;

    /**
     * @type {number}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    maxTeamSize?: number;

    /**
     * @type {number}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    maxTeams?: number;

    /**
     * @type {string}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    name?: string;

    /**
     * @type {DatabaseUser}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    owner?: DatabaseUser;

    /**
     * @type {number}
     * @memberof DefaultControllerGetOwnedClassroomResponse
     */
    ownerId?: number;
}
