/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface GetOwnedClassroomResponse
 */
export interface GetOwnedClassroomResponse {

    /**
     * @type {boolean}
     * @memberof GetOwnedClassroomResponse
     */
    createTeams?: boolean;

    /**
     * @type {string}
     * @memberof GetOwnedClassroomResponse
     */
    description?: string;

    /**
     * @type {string}
     * @memberof GetOwnedClassroomResponse
     */
    gitlabUrl?: string;

    /**
     * @type {number}
     * @memberof GetOwnedClassroomResponse
     */
    groupId?: number;

    /**
     * @type {string}
     * @memberof GetOwnedClassroomResponse
     */
    id?: string;

    /**
     * @type {number}
     * @memberof GetOwnedClassroomResponse
     */
    maxTeamSize?: number;

    /**
     * @type {number}
     * @memberof GetOwnedClassroomResponse
     */
    maxTeams?: number;

    /**
     * @type {string}
     * @memberof GetOwnedClassroomResponse
     */
    name?: string;

    /**
     * @type {User}
     * @memberof GetOwnedClassroomResponse
     */
    owner?: User;

    /**
     * @type {number}
     * @memberof GetOwnedClassroomResponse
     */
    ownerId?: number;

    /**
     * @type {boolean}
     * @memberof GetOwnedClassroomResponse
     */
    studentsViewAllProjects?: boolean;
}
