import { DeepRequired, SubPartial } from "@/types/utils";
import { Assignment as OldAssignment } from "./assignment";
export type Assignment = SubPartial<DeepRequired<OldAssignment>, "dueDate">;
import { AuthGetCsrfResponse as OldAuthGetCsrfResponse } from "./auth-get-csrf-response";
export type AuthGetCsrfResponse = DeepRequired<OldAuthGetCsrfResponse>;
export * from './change-owned-classroom-member-request';
import { Classroom as OldClassroom } from "./classroom";
export type Classroom = DeepRequired<OldClassroom>;
import { ClassroomInvitation as OldClassroomInvitation } from "./classroom-invitation";
export type ClassroomInvitation = DeepRequired<OldClassroomInvitation>;
import { ClassroomInvitationStatus as OldClassroomInvitationStatus } from "./classroom-invitation-status";
export type ClassroomInvitationStatus = DeepRequired<OldClassroomInvitationStatus>;
import { CreateAssignmentRequest as OldCreateAssignmentRequest } from "./create-assignment-request";
export type CreateAssignmentRequest = SubPartial<DeepRequired<OldCreateAssignmentRequest>, "dueDate">;
import { CreateClassroomRequest as OldCreateClassroomRequest } from "./create-classroom-request";
export type CreateClassroomRequest = DeepRequired<OldCreateClassroomRequest>;
import { CreateJoinedTeamRequest as OldCreateJoinedTeamRequest } from "./create-joined-team-request";
export type CreateJoinedTeamRequest = DeepRequired<OldCreateJoinedTeamRequest>;
import { CreateOwnedTeamRequest as OldCreateOwnedTeamRequest } from "./create-owned-team-request";
export type CreateOwnedTeamRequest = DeepRequired<OldCreateOwnedTeamRequest>;
import { GetJoinedClassroomAssignmentResponse as OldGetJoinedClassroomAssignmentResponse } from "./get-joined-classroom-assignment-response";
export type GetJoinedClassroomAssignmentResponse = DeepRequired<OldGetJoinedClassroomAssignmentResponse>;
import { GetJoinedClassroomResponse as OldGetJoinedClassroomResponse } from "./get-joined-classroom-response";
export type GetJoinedClassroomResponse = SubPartial<DeepRequired<OldGetJoinedClassroomResponse>, "team">;
import { GetJoinedClassroomTeamResponse as OldGetJoinedClassroomTeamResponse } from "./get-joined-classroom-team-response";
export type GetJoinedClassroomTeamResponse = DeepRequired<OldGetJoinedClassroomTeamResponse>;
import { GetMeResponse as OldGetMeResponse } from "./get-me-response";
export type GetMeResponse = DeepRequired<OldGetMeResponse>;
import { GetOwnedClassroomAssignmentProjectResponse as OldGetOwnedClassroomAssignmentProjectResponse } from "./get-owned-classroom-assignment-project-response";
export type GetOwnedClassroomAssignmentProjectResponse = DeepRequired<OldGetOwnedClassroomAssignmentProjectResponse>;
import { GetOwnedClassroomMemberResponse as OldGetOwnedClassroomMemberResponse } from "./get-owned-classroom-member-response";
export type GetOwnedClassroomMemberResponse = SubPartial<DeepRequired<OldGetOwnedClassroomMemberResponse>, "team">;
import { GetOwnedClassroomResponse as OldGetOwnedClassroomResponse } from "./get-owned-classroom-response";
export type GetOwnedClassroomResponse = DeepRequired<OldGetOwnedClassroomResponse>;
import { GetOwnedClassroomTeamProjectResponse as OldGetOwnedClassroomTeamProjectResponse } from "./get-owned-classroom-team-project-response";
export type GetOwnedClassroomTeamProjectResponse = DeepRequired<OldGetOwnedClassroomTeamProjectResponse>;
import { GetOwnedClassroomTeamResponse as OldGetOwnedClassroomTeamResponse } from "./get-owned-classroom-team-response";
export type GetOwnedClassroomTeamResponse = DeepRequired<OldGetOwnedClassroomTeamResponse>;
import { HTTPError as OldHTTPError } from "./httperror";
export type HTTPError = DeepRequired<OldHTTPError>;
import { InviteToClassroomRequest as OldInviteToClassroomRequest } from "./invite-to-classroom-request";
export type InviteToClassroomRequest = DeepRequired<OldInviteToClassroomRequest>;
import { JoinClassroomRequest as OldJoinClassroomRequest } from "./join-classroom-request";
export type JoinClassroomRequest = DeepRequired<OldJoinClassroomRequest>;
import { Role as OldRole } from "./role";
export type Role = DeepRequired<OldRole>;
import { Team as OldTeam } from "./team";
export type Team = DeepRequired<OldTeam>;
import { TemplateResponse as OldTemplateResponse } from "./template-response";
export type TemplateResponse = DeepRequired<OldTemplateResponse>;
import { UpdateClassroomRequest as OldUpdateClassroomRequest } from "./update-classroom-request";
export type UpdateClassroomRequest = DeepRequired<OldUpdateClassroomRequest>;
import { User as OldUser } from "./user";
export type User = DeepRequired<OldUser>;
import { UserAvatar as OldUserAvatar } from "./user-avatar";
export type UserAvatar = DeepRequired<OldUserAvatar>;
import { UserClassrooms as OldUserClassrooms } from "./user-classrooms";
export type UserClassrooms = SubPartial<DeepRequired<OldUserClassrooms>, "team">;
