/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Action } from './action';
 /**
 * 
 *
 * @export
 * @interface JoinClassroomRequest
 */
export interface JoinClassroomRequest {

    /**
     * @type {Action}
     * @memberof JoinClassroomRequest
     */
    action: Action;

    /**
     * @type {boolean}
     * @memberof JoinClassroomRequest
     */
    classroomCode: boolean;

    /**
     * @type {string}
     * @memberof JoinClassroomRequest
     */
    invitationId: string;
}
