/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ModelTestReportTestCase } from './model-test-report-test-case';
 /**
 * 
 *
 * @export
 * @interface ModelTestReportTestSuite
 */
export interface ModelTestReportTestSuite {

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    errorCount: number;

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    failedCount: number;

    /**
     * @type {string}
     * @memberof ModelTestReportTestSuite
     */
    name: string;

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    skippedCount: number;

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    successCount: number;

    /**
     * @type {Array<ModelTestReportTestCase>}
     * @memberof ModelTestReportTestSuite
     */
    testCases: Array<ModelTestReportTestCase>;

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    totalCount: number;

    /**
     * @type {number}
     * @memberof ModelTestReportTestSuite
     */
    totalTime: number;
}
