/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Team
 */
export interface Team {

    /**
     * @type {string}
     * @memberof Team
     */
    createdAt: string;

    /**
     * @type {number}
     * @memberof Team
     */
    groupId: number;

    /**
     * @type {string}
     * @memberof Team
     */
    id: string;

    /**
     * @type {string}
     * @memberof Team
     */
    name: string;

    /**
     * @type {string}
     * @memberof Team
     */
    updatedAt: string;
}
