/* tslint:disable */
/* eslint-disable */
/**
 * GitLab Classrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Classroom } from './classroom';
import { Role } from './role';
import { Team } from './team';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface UserClassroomResponse
 */
export interface UserClassroomResponse {

    /**
     * @type {Classroom}
     * @memberof UserClassroomResponse
     */
    classroom: Classroom;

    /**
     * @type {Role}
     * @memberof UserClassroomResponse
     */
    role: Role;

    /**
     * @type {Team}
     * @memberof UserClassroomResponse
     */
    team?: Team;

    /**
     * @type {User}
     * @memberof UserClassroomResponse
     */
    user: User;

    /**
     * @type {string}
     * @memberof UserClassroomResponse
     */
    webUrl: string;
}
