/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our Gitlab Classroom Webapp
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UtilsManualResult } from './utils-manual-result';
 /**
 * 
 *
 * @export
 * @interface UtilsReportDataItem
 */
export interface UtilsReportDataItem {

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    assignmentName: string;

    /**
     * @type {number}
     * @memberof UtilsReportDataItem
     */
    autogradingMaxScore: number;

    /**
     * @type {number}
     * @memberof UtilsReportDataItem
     */
    autogradingScore: number;

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    email: string;

    /**
     * @type {number}
     * @memberof UtilsReportDataItem
     */
    maxScore: number;

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    name: string;

    /**
     * @type {number}
     * @memberof UtilsReportDataItem
     */
    percentage: number;

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    projectId: string;

    /**
     * @type {{ [key: string]: UtilsManualResult; }}
     * @memberof UtilsReportDataItem
     */
    rubricResults: { [key: string]: UtilsManualResult; };

    /**
     * @type {number}
     * @memberof UtilsReportDataItem
     */
    score: number;

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    teamName: string;

    /**
     * @type {string}
     * @memberof UtilsReportDataItem
     */
    username: string;
}
