// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"gitlab.hs-flensburg.de/gitlab-classroom/model/database"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&database.Assignment{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&database.Assignment{}) fail: %s", err)
	}
}

func Test_assignmentQuery(t *testing.T) {
	assignment := newAssignment(db)
	assignment = *assignment.As(assignment.TableName())
	_do := assignment.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(assignment.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <assignments> fail:", err)
		return
	}

	_, ok := assignment.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from assignment success")
	}

	err = _do.Create(&database.Assignment{})
	if err != nil {
		t.Error("create item in table <assignments> fail:", err)
	}

	err = _do.Save(&database.Assignment{})
	if err != nil {
		t.Error("create item in table <assignments> fail:", err)
	}

	err = _do.CreateInBatches([]*database.Assignment{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <assignments> fail:", err)
	}

	_, err = _do.Select(assignment.ALL).Take()
	if err != nil {
		t.Error("Take() on table <assignments> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <assignments> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <assignments> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <assignments> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*database.Assignment{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <assignments> fail:", err)
	}

	_, err = _do.Select(assignment.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <assignments> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <assignments> fail:", err)
	}

	_, err = _do.Select(assignment.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <assignments> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <assignments> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <assignments> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <assignments> fail:", err)
	}

	_, err = _do.ScanByPage(&database.Assignment{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <assignments> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <assignments> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <assignments> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <assignments> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <assignments> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <assignments> fail:", err)
	}
}
