// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"gitlab.hs-flensburg.de/gitlab-classroom/model/database"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&database.ClassroomInvitation{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&database.ClassroomInvitation{}) fail: %s", err)
	}
}

func Test_classroomInvitationQuery(t *testing.T) {
	classroomInvitation := newClassroomInvitation(db)
	classroomInvitation = *classroomInvitation.As(classroomInvitation.TableName())
	_do := classroomInvitation.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(classroomInvitation.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <classroom_invitations> fail:", err)
		return
	}

	_, ok := classroomInvitation.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from classroomInvitation success")
	}

	err = _do.Create(&database.ClassroomInvitation{})
	if err != nil {
		t.Error("create item in table <classroom_invitations> fail:", err)
	}

	err = _do.Save(&database.ClassroomInvitation{})
	if err != nil {
		t.Error("create item in table <classroom_invitations> fail:", err)
	}

	err = _do.CreateInBatches([]*database.ClassroomInvitation{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <classroom_invitations> fail:", err)
	}

	_, err = _do.Select(classroomInvitation.ALL).Take()
	if err != nil {
		t.Error("Take() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <classroom_invitations> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*database.ClassroomInvitation{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Select(classroomInvitation.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Select(classroomInvitation.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <classroom_invitations> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.ScanByPage(&database.ClassroomInvitation{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <classroom_invitations> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <classroom_invitations> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <classroom_invitations> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <classroom_invitations> fail:", err)
	}
}
