// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LoginImport } from "./routes/login"
import { Route as AboutImport } from "./routes/about"
import { Route as AuthImport } from "./routes/_auth"
import { Route as HelloRouteImport } from "./routes/hello/route"
import { Route as IndexImport } from "./routes/index"
import { Route as HelloIndexImport } from "./routes/hello/index"
import { Route as AuthDashboardImport } from "./routes/_auth/dashboard"

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any)

const HelloRouteRoute = HelloRouteImport.update({
  path: "/hello",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const HelloIndexRoute = HelloIndexImport.update({
  path: "/",
  getParentRoute: () => HelloRouteRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  path: "/dashboard",
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/hello": {
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRoute
    }
    "/_auth": {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/about": {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_auth/dashboard": {
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthImport
    }
    "/hello/": {
      preLoaderRoute: typeof HelloIndexImport
      parentRoute: typeof HelloRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  HelloRouteRoute.addChildren([HelloIndexRoute]),
  AuthRoute.addChildren([AuthDashboardRoute]),
  AboutRoute,
  LoginRoute,
])
