// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	AuthAccount  *authAccount
	AuthUser     *authUser
	TokenSession *tokenSession
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AuthAccount = &Q.AuthAccount
	AuthUser = &Q.AuthUser
	TokenSession = &Q.TokenSession
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		AuthAccount:  newAuthAccount(db, opts...),
		AuthUser:     newAuthUser(db, opts...),
		TokenSession: newTokenSession(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AuthAccount  authAccount
	AuthUser     authUser
	TokenSession tokenSession
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AuthAccount:  q.AuthAccount.clone(db),
		AuthUser:     q.AuthUser.clone(db),
		TokenSession: q.TokenSession.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		AuthAccount:  q.AuthAccount.replaceDB(db),
		AuthUser:     q.AuthUser.replaceDB(db),
		TokenSession: q.TokenSession.replaceDB(db),
	}
}

type queryCtx struct {
	AuthAccount  IAuthAccountDo
	AuthUser     IAuthUserDo
	TokenSession ITokenSessionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AuthAccount:  q.AuthAccount.WithContext(ctx),
		AuthUser:     q.AuthUser.WithContext(ctx),
		TokenSession: q.TokenSession.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
